In [1]:
import pyreadstat
import pandas as pd

In [2]:
meals = ["breakfast", "lunch", "dinner", "snack", "drink"]

for meal in meals:
    pd.read_csv(meal+".csv")

In [3]:
pd.read_csv("lunch.csv")

,Unnamed: 0,SID,DayName,NewDayName,DayNumber,MealName,MealName_A,FoodName,Group1,Group2,...,SFA150Pentadecanoicacidg,SFA240LignocericAcidg,Epigallocatechin3gallatemg,Daidzeinmg,Genisteinmg,Glyciteinmg,Totalisoflavonesmg,BiochaninAmg,Formononetinmg,Coumestrolmg
0,0,1101,1.25.19,01.25.19,1,School Lunch,2.0,"Borden 1% lowfat milk (15, 17, 18)",DML0100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1101,1.25.19,01.25.19,1,School Lunch,2.0,"HOT POCKETS Stuffed Sandwich, Pepperoni Pizza,...",GRR0800,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1101,1.25.19,01.25.19,1,School Lunch,2.0,"French Fries, Straight cut oven - 20",VEG0800,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1101,1.25.19,01.25.19,1,School Lunch,2.0,Apple Crisp 12,GRR0800,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1103,1.25.19,01.25.19,1,School Lunch,2.0,"Borden 1% lowfat milk (15, 17, 18)",DML0100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6061,6061,2519,11.21.19,11.21.19,7,Lunch,2.0,Great Value Sweet Brewed Iced Tea,BVS0500,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6062,6062,2519,11.21.19,11.21.19,7,Lunch,2.0,Sausage Pancake on a Stick (19),MCF0100,GRR0800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6063,6063,2521,11.21.19,11.21.19,7,Lunch,2.0,Brown Rice (25),GRW0100,NaN,...,0.001,0.001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6064,6064,2521,11.21.19,11.21.19,7,Lunch,2.0,Sweet Peas (25),VEG0450,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6065,6065,2521,11.21.19,11.21.19,7,Lunch,2.0,"Drink, Lemonade, Prepared from Frozen Concentrate",BVS0300,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
pd.read_csv("w1-census-block.csv")

,Unnamed: 0,SID,Address_Exclude,Total_Population,Total_Housing_Units,Median_Household_Income_InflationAdjusted,Tenure_Total,Total_Owner_occupied,Total_Percent_Owner_occupied,Total_Renter_occupied,...,Families_Total_A,Families_MarriedCoupleFamily,Families_MarriedCoupleFamilieswchildrenunder18,Families_PercentMarriedCoupleFamilieswchildrenunder18,Families_MaleHouseholder_nowife,Families_MaleHouseholder_wchildrenunder18,Families_PercentMaleHouseholder_wchildrenunder19,Families_FemaleHouseholder_nohusband,Families_FemaleHouseholder_wchildrenunder18,Families_PercentFemaleHouseholder_wchildrenunder18
0,0,2308.0,0.0,2125.0,785.0,52303.0,617.0,492.0,79.740681,125.0,...,499.0,391.0,172.0,43.989770,44.0,20.0,0.45454,64.0,14.0,21.875000
1,1,2311.0,0.0,2125.0,785.0,52303.0,617.0,492.0,79.740681,125.0,...,499.0,391.0,172.0,43.989770,44.0,20.0,0.45454,64.0,14.0,21.875000
2,2,2313.0,0.0,2125.0,785.0,52303.0,617.0,492.0,79.740681,125.0,...,499.0,391.0,172.0,43.989770,44.0,20.0,0.45454,64.0,14.0,21.875000
3,3,2315.0,0.0,2125.0,785.0,52303.0,617.0,492.0,79.740681,125.0,...,499.0,391.0,172.0,43.989770,44.0,20.0,0.45454,64.0,14.0,21.875000
4,4,2316.0,0.0,2125.0,785.0,52303.0,617.0,492.0,79.740681,125.0,...,499.0,391.0,172.0,43.989770,44.0,20.0,0.45454,64.0,14.0,21.875000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284,284,1104.0,0.0,6308.0,2475.0,69113.0,2440.0,2199.0,90.122951,241.0,...,1651.0,1231.0,688.0,55.889521,0.0,0.0,999.00000,420.0,265.0,63.095238
285,285,1108.0,0.0,6308.0,2475.0,69113.0,2440.0,2199.0,90.122951,241.0,...,1651.0,1231.0,688.0,55.889521,0.0,0.0,999.00000,420.0,265.0,63.095238
286,286,1109.0,0.0,6308.0,2475.0,69113.0,2440.0,2199.0,90.122951,241.0,...,1651.0,1231.0,688.0,55.889521,0.0,0.0,999.00000,420.0,265.0,63.095238
287,287,1810.0,0.0,6308.0,2475.0,69113.0,2440.0,2199.0,90.122951,241.0,...,1651.0,1231.0,688.0,55.889521,0.0,0.0,999.00000,420.0,265.0,63.095238
288,288,1815.0,0.0,6308.0,2475.0,69113.0,2440.0,2199.0,90.122951,241.0,...,1651.0,1231.0,688.0,55.889521,0.0,0.0,999.00000,420.0,265.0,63.095238

In [5]:
data = pd.read_csv("metadata.txt", delimiter="\t")

In [6]:
data

,Sample_ID,SID,reads_sample,site,female,W1incimp,p1edu1,p1edu2,SES,singlepar,...,Actinobacteriota_ra,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,c1bmiz.1,c1obese.1,c1bmicat.1,c1bmi.1
0,W1x1102,1102,42258,1,1,6.0,1,1,-1.177406,0,...,0.071443,NaN,NaN,NaN,NaN,NaN,1.87,1.0,4.0,27.766506
1,W1x1103,1103,45957,1,0,13.0,2,2,0.026725,0,...,0.026540,NaN,NaN,NaN,NaN,NaN,1.26,0.0,3.0,22.312371
2,W1x1104,1104,4087,1,0,1.0,6,5,-0.469769,1,...,NaN,NaN,NaN,NaN,NaN,NaN,1.45,0.0,3.0,23.312114
3,W1x1106,1106,44104,1,0,6.0,2,2,-0.844857,0,...,0.001767,NaN,NaN,NaN,NaN,NaN,3.07,1.0,6.0,36.374533
4,W1x1110,1110,35098,1,0,3.0,1,1,-1.550941,1,...,0.012079,NaN,NaN,NaN,NaN,NaN,2.84,1.0,6.0,34.844670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,W1x2508,2508,61771,15,0,13.0,7,6,1.356920,0,...,0.046013,NaN,NaN,NaN,NaN,NaN,1.40,0.0,3.0,23.669631
133,W1x2513,2513,47269,15,1,13.0,6,5,1.024371,0,...,0.049258,NaN,NaN,NaN,NaN,NaN,-0.62,0.0,2.0,17.027747
134,W1x2514,2514,54806,15,1,13.0,3,3,0.359273,0,...,0.033524,NaN,NaN,NaN,NaN,NaN,0.27,0.0,2.0,19.684360
135,W1x2515,2515,60982,15,1,13.0,6,5,1.024371,0,...,0.044863,NaN,NaN,NaN,NaN,NaN,1.67,1.0,4.0,26.486424
136,W1x2516,2516,60699,15,0,13.0,3,3,0.359273,0,...,0.046629,NaN,NaN,NaN,NaN,NaN,-0.09,0.0,2.0,18.824315

In [7]:
data.to_csv("metadata.csv")